### ISSUE TITLE
Same icon for two applications

### ISSUE THREAD

**Issue by buddyhollyy** [Cairo-Dock/cairo-dock-core#31]
I have a problem where the Nautilus File Manager uses the Remmina icon. This only happens in Cairo-Dock. 

I attempted to edit the 'Class of the program' setting for my Nautilus shortcut, but when the program is opened, it uses Remmina's icon regardless of what I have entered.

$ xprop | grep WM_CLASS
WM_CLASS(STRING) = "org.gnome.Nautilus", "Org.gnome.Nautilus"

$ xprop | grep WM_CLASS
WM_CLASS(STRING) = "org.remmina.Remmina", "org.remmina.Remmina"

OS: Ubuntu 22.04
![cairo - same icon](https://github.com/user-attachments/assets/60242923-8fcd-487b-94b2-f56bd5c1a5e2)

**Comment by dkondor** [comment]
Hi,

thanks for reporting! I believe that this is likely the same issue as #28 (app_ids truncated) -- in this case, this should be fixed in the beta version (3.5.99). You can try it out by compiling the master branch or installing from the Ubuntu PPA:
https://launchpad.net/~cairo-dock-team/+archive/ubuntu/weekly
If you are able to test, any feedback (on this bug or other issues you might encounter) are very much appreciated!

I'm also considering to backport the fix to the stable version, but the changes are not straightforward and could introduce regressions (TLDR: we do include a lot of workarounds for apps and WMs that do not follow the standards regarding app-ids / class, while the typical format of app-ids also changed in the past years). In any case, that would also be released in the PPA.

**Comment by buddyhollyy** [comment]
Thanks for the advice! I updated to 3.5.99.beta1. This resolved my problem with the duplicate icons.
